[package]
name = "sky130pdk"
version = "0.6.1"
edition = "2021"

[dependencies]
substrate = { version = "0.6.1", registry = "substrate", path = "../../substrate" }
spectre = { version = "0.6.1", registry = "substrate", path = "../../tools/spectre" }

rust_decimal = "1.31"
rust_decimal_macros = "1.31"
indexmap = { version = "2", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
arcstr = { version = "1", features = ["serde"] }
