[package]
name = "sky130pdk"
version = "0.8.1"
edition = "2021"

[dependencies]
substrate = { version = "0.8.1", registry = "substrate", path = "../../substrate" }
scir = { version = "0.7.0", registry = "substrate", path = "../../libs/scir" }
spectre = { version = "0.9.1", registry = "substrate", path = "../../tools/spectre" }
ngspice = { version = "0.3.1", registry = "substrate", path = "../../tools/ngspice" }
spice = { version = "0.7.1", registry = "substrate", path = "../../libs/spice" }

rust_decimal = "1.32"
rust_decimal_macros = "1.32"
indexmap = { version = "2", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
arcstr = { version = "1", features = ["serde"] }
paste = "1"
unicase = "2"

[dev-dependencies]
approx = "0.5"
derive-where = "1"

[features]
spectre = []
