[workspace]

resolver = "2"

members = [
    "cache",
    "config",
    "cli",
    "codegen",
    "dex",
    "diagnostics",
    "digital",
    "drc",
    "gds",
    "geometry",
    "lef",
    "lvs",
    "par",
    "pdks/sky130pdk",
    "pex",
    "sbm",
    "scg",
    "scir",
    "sde",
    "sim",
    "subfile",
    "substrate",
    "substrate-api",
    "tests",
    "timing",
    "netlist/spectre",
    "netlist/spice",
]
