[workspace]

resolver = "2"

members = [
    "codegen",
    "config",
    "libs/cache",
    "libs/gds",
    "libs/geometry",
    "libs/opacity",
    "libs/pathtree",
    "libs/scir",
    "libs/spice",
    "libs/uniquify",
    "pdks/sky130pdk",
    "substrate",
    "tests",
    "tools/spectre",
]

exclude = ["examples"]

