coverage:
  status:
    project:
      default:
        target: 0%
        threshold: 0%
        if_ci_failed: error
        branches: 
          - main
        informational: true
        only_pulls: false
    patch:
      default:
        target: 0%
        threshold: 0%
        branches: 
          - main
        if_ci_failed: error
        informational: true
        only_pulls: false
