[package]
name = "magic_netgen"
version = "0.1.2"
edition = "2021"

[dependencies]
substrate = { version = "0.11.0", registry = "substrate", path = "../../substrate" }
scir = { version = "0.10.0", registry = "substrate", path = "../../libs/scir" }
spice = { version = "0.10.0", registry = "substrate", path = "../../libs/spice" }
magic = { version = "0.3.0", registry = "substrate", path = "../magic" }
netgen = { version = "0.3.0", registry = "substrate", path = "../netgen" }
