[package]
name = "substrate_api_examples"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
substrate = { version = "0.10.0", registry = "substrate" }
scir = { version = "0.9.0", registry = "substrate" }

arcstr = "1"
rust_decimal = "1.30"
rust_decimal_macros = "1.30"
