[package]
name = "quantus"
version = "0.0.0"
edition = "2021"

[dependencies]
tera = "1"
lazy_static = "1"
serde = { version = "1", features = ["derive"] }
anyhow = "1"
regex = "1"

substrate = { version = "0.8.1", path = "../../substrate" }
scir = { version = "0.7.0", path = "../../libs/scir" }
spice = { version = "0.7.1", path = "../../libs/spice" }
pegasus = { version = "0.0.0", path = "../pegasus" }

[dev-dependencies]
rust_decimal = "1"
rust_decimal_macros = "1"
spectre = { version = "0.9.1", path = "../spectre" }
approx = "0.5"
