[package]
name = "quantus"
version = "0.0.0"
edition = "2021"

[dependencies]
tera = "1"
lazy_static = "1"
serde = { version = "1", features = ["derive"] }
anyhow = "1"
regex = "1"

[dev-dependencies]
pegasus = { version = "0.0.0", path = "../pegasus" }
