[package]
name = "sky130_inverter"
version = "0.0.0"
edition = "2021"
publish = false

# begin-code-snippet dependencies
[dependencies]
substrate = { version = "0.11.0", registry = "substrate" }
sky130 = { version = "0.11.0", registry = "substrate" }
layir = { version = "0.3.0", registry = "substrate" }
gdsconv = { version = "0.3.0", registry = "substrate" }
gds = { version = "0.5.0", registry = "substrate" }
scir = { version = "0.10.0", registry = "substrate" }
spice = { version = "0.10.0", registry = "substrate" }

arcstr = "1"
rust_decimal = "1.30"
rust_decimal_macros = "1.30"
# end-code-snippet dependencies

# begin-code-snippet open-dependencies
ngspice = { version = "0.6.0", registry = "substrate" }
magic_netgen = { version = "0.1.2", registry = "substrate" }
magic = { version = "0.3.0", registry = "substrate" }
# end-code-snippet open-dependencies

# begin-code-snippet cds-dependencies
spectre = { version = "0.12.0", registry = "substrate" }
quantus = { version = "0.3.0", registry = "substrate" }
pegasus = { version = "0.3.0", registry = "substrate" }
# end-code-snippet cds-dependencies
