[package]
name = "layout"
version = "0.0.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
geometry = { version = "0.1.0", registry = "substrate", path = "../geometry" }
