[package]
name = "codegen"
version = "0.10.0"
edition = "2021"

[dependencies]
darling = "0.20"
syn = { version = "2" }
quote = "1"
proc-macro2 = "1"
proc-macro-crate = "1"
convert_case = "0.6"

snippets = { version = "0.7.0", registry = "substrate", path = "../docs/snippets" }
macrotools = { version = "0.2.0", registry = "substrate", path = "../libs/macrotools" }

[build-dependencies]
snippets = { version = "0.7.0", registry = "substrate", path = "../docs/snippets" }
examples = { version = "0.2.0", registry = "substrate", path = "../examples" }

[lib]
proc-macro = true
