[package]
name = "codegen"
version = "0.2.0"
edition = "2021"
include = ["src", "build/docs"]

[dependencies]
darling = "0.20"
syn = { version = "2", features = ["full"] }
quote = "1"
proc-macro2 = "1"
proc-macro-crate = "1"
proc-macro-error = "1"
convert_case = "0.6"

[dev-dependencies]
arcstr = "1"
serde = { version = "1", features = ["derive"] }
substrate = { version = "<=0.2.0", registry = "substrate", path = "../substrate" }
sky130pdk = { version = "<=0.2.0", registry = "substrate", path = "../pdks/sky130pdk" }

[lib]
proc-macro = true
