[package]
name = "codegen"
version = "0.8.1"
edition = "2021"

[dependencies]
darling = "0.20"
syn = { version = "2" }
quote = "1"
proc-macro2 = "1"
proc-macro-crate = "1"
proc-macro-error = "1"
convert_case = "0.6"

examples = { version = "0.5.1", registry = "substrate", path = "../docs/examples" }
type_dispatch = { version = "0.3.0", registry = "substrate", path = "../libs/type_dispatch" }

[dev-dependencies]
arcstr = "1"
substrate = { version = "<=0.8.1", registry = "substrate", path = "../substrate" }
sky130pdk = { version = "<=0.8.1", registry = "substrate", path = "../pdks/sky130pdk" }
spectre = { version = "<=0.9.1", registry = "substrate", path = "../tools/spectre" }
spice = { version = "<=0.7.1", registry = "substrate", path = "../libs/spice" }
rust_decimal = "1.30"
rust_decimal_macros = "1.30"

[lib]
proc-macro = true
