[package]
name = "via"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
substrate = { version = "0.10.2", registry = "substrate" }
layir = { version = "0.2.1", registry = "substrate" }
