[package]
name = "colbuf"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
substrate = { version = "0.8.1", registry = "substrate", path = "../../../substrate" }
spice = { version = "0.7.1", registry = "substrate", path = "../../../libs/spice" }
spectre = { version = "0.9.1", registry = "substrate", path = "../../../tools/spectre" }
ngspice = { version = "0.3.1", registry = "substrate", path = "../../../tools/ngspice" }
quantus = { version = "0.0.0", registry = "substrate", path = "../../../tools/quantus" }
magic_netgen = { version = "0.0.0", registry = "substrate", path = "../../../tools/magic_netgen" }
rust_decimal = "1.36.0"
rust_decimal_macros = "1.36.0"

[dev-dependencies]
approx = "0.5"
