[package]
name = "colbuf"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
substrate = { version = "0.8.2", registry = "substrate", path = "../../substrate" }
spice = { version = "0.7.2", registry = "substrate", path = "../../libs/spice" }
spectre = { version = "0.9.2", registry = "substrate", path = "../../tools/spectre" }
ngspice = { version = "0.3.2", registry = "substrate", path = "../../tools/ngspice" }
quantus = { version = "0.1.0", registry = "substrate", path = "../../tools/quantus" }
magic-netgen = { version = "0.0.1", registry = "substrate", path = "../../tools/magic-netgen" }
rust_decimal = "1.36.0"
rust_decimal_macros = "1.36.0"

[dev-dependencies]
approx = "0.5"
