[package]
name = "geometry"
version = "0.0.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
array_map = { version = "0.4", features = ["derive", "serde", "std"] }
thiserror = "1.0.40"
