[package]
name = "spectre"
version = "0.10.0"
edition = "2021"

[dependencies]
rust_decimal = "1.32"
rust_decimal_macros = "1.32"
thiserror = "1"
arcstr = { version = "1", features = ["serde"] }
tera = "1"
lazy_static = "1"
serde = { version = "1", features = ["derive"] }
tracing = "0.1"
itertools = "0.11"
psfparser = "0.1.2"
regex = "1.10.2"
num = { version = "0.4.1", features = ["serde"] }

cache = { version = "0.6.0", registry = "substrate", path = "../../libs/cache" }
scir = { version = "0.8.0", registry = "substrate", path = "../../libs/scir" }
substrate = { version = "0.9.0", registry = "substrate", path = "../../substrate" }
spice = { version = "0.8.0", registry = "substrate", path = "../../libs/spice" }
type_dispatch = { version = "0.4.0", registry = "substrate", path = "../../libs/type_dispatch" }

[dev-dependencies]
approx = "0.5"
