[package]
name = "cdl2spice"
version = "0.3.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.6", features = ["derive"] }
scir = { version = "0.10.0", registry = "substrate", path = "../../libs/scir" }
spice = { version = "0.10.0", registry = "substrate", path = "../../libs/spice" }
arcstr = "1"
