[package]
name = "config"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
lazycell = "1"
serde = { version = "1", features = ["derive"] }
toml_edit = "0.19"
log = "0.4"
toml = "0.7"
windows-sys = "0.48"

[target.'cfg(windows)'.dependencies.windows-sys]
features = [
  "Win32_Foundation",
  "Win32_UI_Shell",
]
