[package]
name = "config"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
url = "2.4.0"
lazycell = "1.3.0"
serde = { version = "1.0.164", features = ["derive"] }
toml_edit = "0.19.10"
curl = "0.4.44"
log = "0.4.19"
toml = "0.7.4"
