[package]
name = "config"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
lazycell = "1"
serde = { version = "1", features = ["derive"] }
toml_edit = "0.19"
log = "0.4"
toml = "0.7"

[target.'cfg(windows)'.dependencies.windows-sys]
version = "0.48"
features = [
  "Win32_Foundation",
  "Win32_Storage_FileSystem",
  "Win32_System_Console",
  "Win32_System_Threading",
  "Win32_System_JobObjects",
]
