[package]
name = "spice"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
scir = { version = "0.0.0", registry = "substrate", path = "../../scir" }
opacity = { version = "0.0.0", path = "../../libs/opacity", registry = "substrate" }
