[package]
name = "via"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
substrate = { version = "0.11.0", registry = "substrate", path = "../../../substrate" }
layir = { version = "0.3.0", registry = "substrate", path = "../../../libs/layir" }
