[package]
name = "substrate"
version = "0.2.0"
edition = "2021"
include = ["src", "build/docs"]

[dependencies]
serde = { version = "1", features = ["derive"] }
arcstr = { version = "1", features = ["serde"] }
anyhow = "1"
thiserror = "1"
once_cell = "1"
impl-trait-for-tuples = "0.2"
tracing = "0.1"
rust_decimal = "1"
rust_decimal_macros = "1"
ena = "0.14"
duplicate = "1"
derive_builder = "0.12"
slotmap = "1"
downcast-rs = "1"

config = { version = "0.1.0", registry = "substrate", path = "../config" }
cache = { version = "0.1.0", registry = "substrate", path = "../libs/cache" }
codegen = { version = "0.2.0", registry = "substrate", path = "../codegen" }
geometry = { version = "0.2.0", registry = "substrate", path = "../libs/geometry" }
gds = { version = "0.1.0", registry = "substrate", path = "../gds" }
opacity = { version = "0.1.0", path = "../libs/opacity", registry = "substrate" }
scir = { version = "0.1.0", registry = "substrate", path = "../scir" }
pathtree = { version = "0.1.0", registry = "substrate", path = "../libs/pathtree" }
uniquify = { version = "0.1.0", registry = "substrate", path = "../libs/uniquify" }
spice = { version = "0.0.0", registry = "substrate", path = "../libs/spice" }

[dev-dependencies]
toml = "0.7"
approx = "0.5"
sky130pdk = { version = "<=0.2.0", registry = "substrate", path = "../pdks/sky130pdk" }
