[package]
name = "substrate"
version = "0.0.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1", features = ["derive"] }
arcstr = "1"
thiserror = "1"
once_cell = "1"

geometry = { version = "0.1", registry = "substrate", path = "../geometry" }

[dev-dependencies]
crossbeam-channel = "0.5"

