[package]
name = "scir"
version = "0.1.0"
edition = "2021"

[dependencies]
arcstr = { version = "1", features = ["serde"] }
rust_decimal = "1.30"
rust_decimal_macros = "1.30"
tracing = "0.1"
serde = "1"

diagnostics = { version = "0.0.0", path = "../diagnostics", registry = "substrate" }
