# Global site configuration (user specified)
[site]
versions = ["main", "dev"]

# Docusaurus configuration (can be overwritten by the site builder)
[docusaurus]
current_version = "main"
banner = "unreleased"
base_url = "/"
edit_url = "https://github.com/substrate-labs/substrate2/tree/main/docs/docusaurus"
