name: check-workspace

on:
  workflow_call:

env:
    CARGO_TERM_COLOR: always

jobs:
  lint:
    name: lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install Protoc
        uses: arduino/setup-protoc@v2
      - name: Install Rust
        uses: dtolnay/rust-toolchain@1.70.0
        id: toolchain
        with:
          toolchain: stable
          components: clippy
      - name: Cache workspace
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ steps.toolchain.outputs.cachekey }}
          workspaces: ". -> target"
      - name: Install `cargo-hack`
        uses: taiki-e/install-action@cargo-hack
      - uses: extractions/setup-just@v1
      - name: Generate examples
        run: just gen-examples
      - name: Check formatting
        run: |
          cargo fmt --check
      - name: Lint
        run: |
          cargo hack --feature-powerset clippy --locked -- -D warnings
      - name: Lint examples
        run: |
          cargo hack --feature-powerset clippy --locked -- -D warnings
        working-directory: examples
  check-docs:
    name: check-docs
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install Protoc
        uses: arduino/setup-protoc@v2
      - name: Install Rust
        uses: dtolnay/rust-toolchain@1.70.0
        id: toolchain
        with:
          toolchain: stable
          components: clippy
      - name: Cache workspace
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ steps.toolchain.outputs.cachekey }}
          workspaces: ". -> target"
      - name: Install `cargo-hack`
        uses: taiki-e/install-action@cargo-hack
      - uses: extractions/setup-just@v1
      - name: Generate examples
        run: just gen-examples
      - name: Check docs
        run: |
          cargo hack --all rustdoc --all-targets --all-features -- -D warnings
  test:
    name: test
    runs-on: [bwrc, nfs]
    steps:
      - uses: actions/checkout@v3
      - name: Install Protoc
        uses: arduino/setup-protoc@v2
      - name: Install Rust
        uses: dtolnay/rust-toolchain@1.70.0
        id: toolchain
        with:
          toolchain: stable
          components: clippy
      - uses: extractions/setup-just@v1
      - name: Generate examples
        run: just gen-examples
      - name: Test
        run: cargo test --locked --all-features
      - name: Test examples
        run: cargo test --locked --all-features
        working-directory: examples
  check-docs-site:
    name: check-docs-site
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
          cache-dependency-path: docs/substrate/yarn.lock
      - run: yarn install
        working-directory: docs/substrate
      - run: yarn build
        working-directory: docs/substrate

