name: check-workspace

on:
  workflow_call:
    inputs:
      workspace_path:
        required: true
        type: string
      locked:
        default: false
        type: boolean

env:
    CARGO_TERM_COLOR: always

jobs:
  lint:
    name: lint
    runs-on: bwrc
    steps:
      - uses: actions/checkout@v4
      - name: Check formatting
        run: |
          cargo fmt --check
        working-directory: ${{ inputs.workspace_path }}
      - name: Lint locked
        if: ${{ inputs.locked }}
        run: |
          cargo hack clippy --feature-powerset --locked -- -D warnings
        working-directory: ${{ inputs.workspace_path }}
      - name: Lint tests locked
        if: ${{ inputs.locked }}
        run: |
          cargo hack clippy --feature-powerset --tests --locked -- -D warnings
        working-directory: ${{ inputs.workspace_path }}
      - name: Lint
        if: ${{ ! inputs.locked }}
        run: |
          cargo hack clippy --feature-powerset -- -D warnings
        working-directory: ${{ inputs.workspace_path }}
      - name: Lint tests
        if: ${{ ! inputs.locked }}
        run: |
          cargo hack clippy --feature-powerset --tests -- -D warnings
        working-directory: ${{ inputs.workspace_path }}
  test:
    name: test
    runs-on: bwrc
    steps:
      - uses: actions/checkout@v4
      - name: Test locked
        if: ${{ inputs.locked }}
        run: cargo test --locked --all-features
        working-directory: ${{ inputs.workspace_path }}
      - name: Test
        if: ${{ ! inputs.locked }}
        run: cargo test --all-features
        working-directory: ${{ inputs.workspace_path }}
