name: CI

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

env:
    CARGO_TERM_COLOR: always

jobs:
  release-please:
    runs-on: ubuntu-22.04
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: rust
          package-name: substrate
          command: manifest
  check-workspace:
    uses: ./.github/workflows/check-workspace.yml
  publish-crates:
    name: Publish crates
    runs-on: ubuntu-22.04
    needs: [ release-please, check-workspace ]
    steps:
      - uses: actions/checkout@v3
        with:
          path: rust-ci
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        id: toolchain
        with:
          toolchain: stable
          components: clippy
      - name: Clone `cargo-workspaces`
        uses: actions/checkout@v3
        with:
          repository: rohanku/cargo-workspaces
          path: cargo-workspaces
          ref: dev
      - name: Cache workspace
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ steps.toolchain.outputs.cachekey }}
          workspaces: |
            rust-ci -> target
            cargo-workspaces/cargo-workspaces -> target
      - name: Install `cargo-workspaces`
        working-directory: cargo-workspaces/cargo-workspaces
        run: cargo install --path . --features ssh
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Publish crates
        working-directory: rust-ci
        run: cargo workspaces publish --from-git --token=${{ secrets.KTRA_TOKEN }} --registry=ktra --yes

