name: ci

on:
  pull_request:

env:
    CARGO_TERM_COLOR: always

jobs:
  check-repo:
    uses: ./.github/workflows/check-repo.yml
    with:
      check-release-examples: ${{ ! startsWith(github.head_ref, 'release-please--') }}
