name: ci

on:
  pull_request:

env:
    CARGO_TERM_COLOR: always

jobs:
  check-workspace:
    uses: ./.github/workflows/check-workspace.yml
    with:
      check-release-examples: ${{ ! startsWith(github.ref, 'release-please--') }}
