name: Report code coverage

on:
  workflow_call:

env:
    CARGO_TERM_COLOR: always

jobs:
  coverage:
    name: coverage
    runs-on: bwrc
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        id: toolchain
        with:
          toolchain: nightly
      - name: Run tests
        run: cargo +nightly test --verbose --locked --all-features
        env:
          CARGO_INCREMENTAL: '0'
          RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cinstrument-coverage'
          RUSTDOCFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cinstrument-coverage'
          LLVM_PROFILE_FILE: grcov-%p-%m.profraw
      - name: rust-grcov
        id: grcov
        uses: actions-rs/grcov@v0.1.6
      - name: Codecov
        uses: codecov/codecov-action@v3.1.4
        with:
          verbose: true
          fail_ci_if_error: true
