name: Report code coverage

on:
  workflow_call:

env:
    CARGO_TERM_COLOR: always

jobs:
  coverage:
    name: coverage
    runs-on: [bwrc, nfs]
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: cargo +nightly test --locked --all-features --no-fail-fast
        env:
          CARGO_INCREMENTAL: '0'
          RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off'
          RUSTDOCFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off'
          LLVM_PROFILE_FILE: grcov-%p-%m.profraw
      - name: rust-grcov
        id: grcov
        uses: actions-rs/grcov@v0.1.6
      - name: Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
          fail_ci_if_error: true
