name: deploy-docs

on:
  workflow_call:
    inputs:
      name:
        type: string
  workflow_dispatch:
    inputs:
      name:
        type: string

env:
    CARGO_TERM_COLOR: always
    DOCS_NAME: ${{ inputs.name || github.ref.name }}
    PUBLIC_DOCS_DIR: /tools/C/rahulkumar/substrate_docs_public

jobs:
  deploy-docs:
    name: Deploy documentation
    runs-on: bwrc
    environment: docs
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: 0.3.66
      - run: ./deploy.sh ${{ env.PUBLIC_DOCS_DIR }} ${{ inputs.name || github.ref_name }}
        working-directory: docs/docusaurus
        env:
          FLY_ACCESS_TOKEN: ${{ secrets.FLY_API_TOKEN_DOCS }}

