name: deploy-release-api-docs

on:
  release:
    types: [created]

jobs:
  deploy-api-docs:
    name: Deploy API documentation
    runs-on: bwrc
    needs: [ check-workspace ]
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@ddcac349402ef55840d9870785f4df1890768078
      - run: just build
        working-directory: docs/api
      - run: |
          rm -rf /tools/C/rohankumar/substrate_docs_public/api/release && \
          cp -r target/doc /tools/C/rohankumar/substrate_docs_public/api/release
        working-directory: docs/api
      - run: flyctl deploy --remote-only --detach
        working-directory: /tools/C/rohankumar/substrate_docs_public/api
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_API }}
