name: deploy-docs

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      name:

env:
    CARGO_TERM_COLOR: always
    DOCS_NAME: ${{ inputs.name || github.ref.name }}
    PUBLIC_DOCS_DIR: /Users/rohan/Downloads/substrate_docs_public

jobs:
  deploy-api-docs:
    name: Deploy API documentation
    runs-on: bwrc
    environment: docs
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@ddcac349402ef55840d9870785f4df1890768078
      - run: just build
        working-directory: docs/api
      - run: |
          rm -rf ${{ env.PUBLIC_DOCS_DIR }}/api/${{ inputs.name || github.ref_name }} && \
          mkdir -p ${{ env.PUBLIC_DOCS_DIR }}/api/${{ inputs.name || github.ref_name }} && \
          cp -r target/doc/* ${{ env.PUBLIC_DOCS_DIR }}/api/${{ inputs.name || github.ref_name }}
        working-directory: docs/api
      - run: flyctl deploy --remote-only --detach
        working-directory: ${{ env.PUBLIC_DOCS_DIR }}/api
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_API }}
  deploy-docs:
    name: Deploy documentation
    runs-on: bwrc
    environment: docs
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
          cache-dependency-path: docs/docusaurus/yarn.lock
      - run: yarn install
        working-directory: docs/docusaurus
      - run: yarn build 
        working-directory: docs/docusaurus
      - run: |
          rm -rf ${{ env.PUBLIC_DOCS_DIR }}/docusaurus/branch/${{ inputs.name || github.ref_name }} && \
          mkdir -p ${{ env.PUBLIC_DOCS_DIR }}/docusaurus/branch/${{ inputs.name || github.ref_name }} && \
          cp -r build/* ${{ env.PUBLIC_DOCS_DIR }}/docusaurus/branch/${{ inputs.name || github.ref_name }}
        working-directory: docs/docusaurus
      - run: flyctl deploy --remote-only --detach
        working-directory: ${{ env.PUBLIC_DOCS_DIR }}/docusaurus
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_DOCS }}

