name: Cargo audit

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  security-audit:
    runs-on: ubuntu-22.04
    steps:
      - name: Install Rust
        uses: dtolnay/rust-toolchain@1.70.0
      - uses: actions/checkout@v3
      - name: Install cargo-audit
        run: cargo install cargo-audit
      - name: Generate lockfile
        run: cargo generate-lockfile
      - name: Audit dependencies
        run: cargo audit
